config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/cookbook", to: "pages#cookbook"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:show, :index, :create, :new] do
    resources :user_favorites, only: [:create]
    resources :user_ratings, only: [:create, :update]
  end

  resources :user_favorites, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :recipes_ingredients
  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipes_ingredients, dependent: :destroy
  accepts_nested_attributes_for :recipes_ingredients, reject_if: proc { |attributes| attributes[:ingredient_id].blank? }
  has_many :user_favorites, dependent: :destroy
  has_many :ingredients, through: :recipes_ingredients
  has_one_attached :image, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :instructions, presence: true
  validates :era, presence: true

  has_one_attached :photo

  has_many :user_ratings, dependent: :destroy
  # geocoded_by :country_code
  # after_validation :geocode, if: :will_save_change_to_country_code?

  # accepts_nested_attributes_for :ingredients, reject_if: proc { |attributes|
  # attributes['name'].blank? }, allow_destroy: true
end

app/models/recipes_ingredient.rb
class RecipesIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :user_favorites

  has_many :user_ratings
  has_many :recipes

  validates :email, presence: true
  validates :name, presence: true
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :recipe, uniqueness: {scope: :user}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo, :username])

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def cookbook
    @recipes = current_user.recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :recipes_list, only: [:index, :show]

  def index
  end

  def show
    @recipe = Recipe.find(params[:id])
    @blank_stars = 5 - @recipe.rating.to_i
    if user_signed_in?
      @user_favorite = current_user.user_favorites.find_by(recipe: @recipe)
      @user_favorite = UserFavorite.new if @user_favorite.nil?
      @user_rating = current_user.user_ratings.find_by(recipe: @recipe)
      @user_rating = UserRating.new if @user_rating.nil?
    end
  end

  def new
    @recipe = Recipe.new
    @recipe.user = current_user
    @recipe.recipes_ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def recipes_list
    if params[:ingredients]
      @recipes = Recipe.joins(:recipes_ingredients).where("recipes_ingredients.ingredient_id IN (?)", params[:ingredients])
      # TODO: find a better way of doing this (THIS IS HORRIBLE)
      @recipes = @recipes.select { |recipe| @recipes.to_a.count(recipe) >= params[:ingredients].length }.uniq

    elsif params[:query]
      @recipes = Recipe.where('instructions ILIKE :search_query OR country ILIKE :search_query OR recipes.name ILIKE :search_query', search_query: "%#{params[:query]}%")
    else
      @recipes = Recipe.all
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :era, :country, :country_code, :instructions, :prep_time, :photo, recipes_ingredients_attributes: {})
  end
end

app/controllers/recipes_ingredients_controller.rb
class RecipesIngredientsController < ApplicationController
  def index
    @recipes_ingredients = RecipesIngredient.all
  end
end

app/controllers/user_favorites_controller.rb
class UserFavoritesController < ApplicationController
  def index
    @user_favorites = UserFavorite.all
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @user_favorite = UserFavorite.new
  end

  # Needs to be check
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @user_favorite = UserFavorite.new
    @user_favorite.recipe = @recipe

    @user_favorite.user = current_user

    if @user_favorite.save
      redirect_to recipe_path(@recipe), notice: 'Added in favorites'
    else
      redirect_to recipe_path(@recipe), notice: "There was an error"
    end
  end
  #---------------

  def destroy
    @user_favorite = UserFavorite.find(params[:id])
    #@recipe = Recipe.find(params[:id])
    @user_favorite.destroy
    redirect_to recipe_path(@user_favorite.recipe), notice: 'Removed from favorites'
  end
end

app/controllers/user_ratings_controller.rb
class UserRatingsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @user_rating = UserFavorite.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @user_rating = UserRating.new(rating_params)
    @user_rating.recipe = @recipe

    @user_rating.user = current_user

    if @user_rating.save
      update_recipe_rating
      redirect_to recipe_path(@recipe), notice: 'Rated'
    else
      redirect_to recipe_path(@recipe)
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @user_rating = UserRating.find(params[:id])
    @user_rating.update(rating_params)
    update_recipe_rating
    redirect_to recipe_path(@recipe), notice: 'Rate updated'
  end

  private

  def update_recipe_rating
    @recipe.rating = @recipe.user_ratings.sum(:vote) / @recipe.user_ratings.count
    @recipe.save!
  end

  def rating_params
    params.require(:user_rating).permit(:vote)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def cookbook
    @cookbook = UserFavorite.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ancient Meals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

<link rel="apple-touch-icon" sizes="57x57" href="/../../assets/images/icons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/../../assets/images/icons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/../../assets/images/icons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/../../assets/images/icons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/../../assets/images/icons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/../../assets/images/icons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/../../assets/images/icons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/../../assets/images/icons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/../../assets/images/icons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/../../assets/images/icons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/../../assets/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/../../assets/images/icons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/../../assets/images/icons/favicon-16x16.png">

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/../../assets/images/icons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<%= favicon_link_tag asset_path('icons/favicon.ico') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/cookbook.html.erb
<%# <div class="recipe-text-2">cookbook</div> %>
<hr>
<div class="user-info">

<div id="bg-image">
<div class="row">
<div class="container-100">
  <div class="user-container">
  <div class="padding-info-user">
    <div class="avatar">

    <% if current_user.photo.attached? %>

      <%= cl_image_tag current_user.photo.key, class: "avatar-large", alt: "avatar-large" %>
    <% else %>
      <%= image_tag "avatar_placeholder.jpg", class: "avatar-large", alt: "avatar-large" %>
    <% end %>
    </div>
    <div class="padding-p">
      <h6 class="user_name"><strong><%= current_user.name %></strong></h6>
      <h6 class="user_name"><strong>Recipes In Total:</strong> <%= current_user.user_favorites.count + current_user.recipes.count%></h6>
      <h6 class="last-child"><strong>Total Favorite Recipes:</strong> <%= current_user.user_favorites.count %></h6>
    </div>
  </div>
    <div class="user-info">

  <div class="flex-container-">

    <div class="box-2" data-controller="search">
    <br>
      <h3 class="h3-margin-titles"> / Own recipes</h3>
      <%= render "recipes/recipe_list" %>
      <!-- USER FAVORITES LIST -->
      <br>
      <h3 class="h3-margin-titles">/ Favorite recipes</h3>
      <%= render "recipes/favorites" %>
      <!-- USER FAVORITES LIST END-->
    </div>
    </div>
  </div>
</div>

  <div class="image-container">
    <%# <%= image_tag "cookbook_img2.jpg" , class: "bottom-image-3" %>
  </div>




  </div>
    <div class="recipe-container">
        <%# <%= image_tag "Cookbook_img1.jpeg" , class: "bottom-image-2" %>
        <%# <img id="image" /> %>
    </div>
</div>

</div>

app/views/pages/home.html.erb
<hr>
<div id="container-home">


  <div id="left">
      <div class="title-container"><span class="maintitle">Find Ancient Recipes</span>
    </div>

    <div class="homeimg"><%= image_tag "background_horses.jpg" , class: "home-image" %>
    </div>
  </div>
  <div id="right">
    <div class="cocktail-container">
    <%= image_tag "Frame-10.jpg" , class: "cocktail-img" %>
    <span class="cocktail-title"><a href="https://www.patreon.com/" target="_blank">Support us by sending us a meal</a></span>
    </div>


    <div class="cocktail-container-bottom">
    <%= image_tag "Frame-9.jpg" , class: "crap-img" %>
    <span class="cocktail-bottom-title"> <span class="caps-2">W</span>e are a small community of culinary and ancient history fans. We love to go back in time and revitalize old recipes there are so many hidden gems out there. Our goal is to make the best platform available for collecting and archiving recipes that are nowhere else to be found on the big wide web. </span>
    <div class="btn-search-by"> <%= link_to "Search by ingredient", recipes_path, class: "nav-link" %></div>
    </div>
  </div>



</div>

app/views/recipes/_add_to_cookbook.html.erb
<%# <div class="placement"> %>
      <%# <div class="heart"> %>

  <% if user_signed_in? %>
    <% if @user_favorite.persisted? %>
    <%# Link to delete user favorite %>

      <%= link_to(user_favorite_path(@user_favorite), method: :delete) do %>
        <div class="heart is-active"></div>
      <% end %>

    <% else %>

      <%= simple_form_for([@recipe, @user_favorite]) do |f| %>
        <% f.input :recipe %>
        <%= f.button :submit, class: 'heart', value: "", data: { disable_with: "" } %>
      <% end %>
    <% end %>
  <% end %>

      <%# </div> %>
<%# </div> %>

app/views/recipes/_favorites.html.erb
<%# User Favorites List %>
<div class="recipe-list" data-search-target="list">
  <% if @recipes.empty? && current_user.user_favorites.empty? %>
    <p>No favorites</p>
  <% end %>
  <% current_user.user_favorites.each do |fav|%>
    <%= link_to recipe_path(fav.recipe_id), class: "recipe-link" do %>
    <hr />
    <div class="alignment-container mb-0 mt-2">
      <div class="mr-2">
        <h5 class=""><%= fav.recipe.name %></h5>
        <p class=""><%= fav.recipe.user.name %></p>
      </div>
        <p class="p-3"><%= fav.recipe.country %></p>
    </div>
    <div class="mb-1 mt-2 mr-1 text-end">
    </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/_rate.html.erb
<div class="rate_form" data-controller="rate">
    <p class="recipe-rating"><% @recipe.rating.to_i.times do |number|  %>
        <i class="fas fa-carrot"data-action="click->rate#goToForm" data-number="<%= number+1 %>"></i>
      <% end %>
      <% @blank_stars.times do |number|%>
        <i id="empty-carrot" class="fas fa-carrot empty"data-action="click->rate#goToForm" data-number="<%= number+1+@recipe.rating.to_i %>"></i>
      <% end %>
</p>
<% if user_signed_in? %>
    <div class="hidden">
      <%= simple_form_for([@recipe, @user_rating], remote: true) do |f| %>
        <%= f.input :vote,  as: :radio_buttons,  collection: [1,2,3,4,5], class: 'rate', input_html: { data: { action: "change->rate#rateThis" } } %>
        <%= f.button :submit, 'rate this recipe', class: 'hidden', data: { rate_target: "button" } %>
      <% end %>
    </div>
<% end %>
</div>

app/views/recipes/_recipe_list.html.erb
<div class="recipe-list" data-search-target="list">
  <% if @recipes.empty? %>
    <p class="no-results-notice">No results match this search</p>
  <% end %>
  <% @recipes.each do |recipe|%>
    <%= link_to recipe_path(recipe), class: "recipe-link" do %>
    <hr />
    <div class="alignment-container mb-0 mt-2">
      <div class="mr-2">
        <h5 class=""><%= recipe.name %></h5>
        <p class=""><%= recipe.user.name %></p>
      </div>
         <%# <%= render "add_to_cookbook"  %>
        <p class="p-3"><%= recipe.country %></p>
    </div>
    <div class="mb-1 mt-2 mr-1 text-end">
    </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/_recipes_ingredient_fields.html.erb
<div class='nested-fields'>
  <div class="row">
    <div class="col-6">
      <%= f.input :ingredient_id, collection: Ingredient.all.order('name ASC').map { |ingredient| [ingredient.name.capitalize, ingredient.id] }, label: false,
        input_html: { data: { recipe_form_target: "ingredientInput", action: "change->recipe-form#updateIngredients" } } %>
    </div>
    <div class="col-6">
      <%= f.input :quantity, label: false,
      input_html: { data: { recipe_form_target: "ingredientQuantityInput", action: "change->recipe-form#updateIngredients" } }%>
    </div>
  </div>
</div>

app/views/recipes/_search_form.html.erb
<div id="centerbar-recipe">
  <form action="/recipes" method="get">
    <select multiple name="ingredients[]" data-controller="select2" data-search-target="input">
      <% Ingredient.all.each do |ing|  %>
        <option value="<%= ing.id %>"><%= ing.name.capitalize %></option>
      <% end %>
    </select>
  </form>
</div>
 <!--hello-->

app/views/recipes/_show_recipe.html.erb
<div class="container-recipe-info container-fluid">
  <div class="row">
    <div class="col-lg-1">
      <%= render "add_to_cookbook" %>
    </div>
    <div class="col-lg-11">
      <p class="recipe-country"><%= @recipe.country %></p>
    </div>
  </div>

  <div class="row info-line">
    <div class="col-lg-4">
      <h1 class="recipe-name"><%= @recipe.name %></h1>
    </div>
    <div class="col-lg-3">
      <p class="recipe-by">By <%= @recipe.user.name %></p>
    </div>


    <div class="col-lg-5 info-right">
      <p class="recipe-prep-time"><%= @recipe.prep_time %> prep / </p>
      <p class="recipe-era"><%= @recipe.era %> / </p>
      <p class="recipe-rate"><%= render "rate" %></p>
    </div>
  </div>



  <div class="row mt-5">

    <!--Buttons ...Lali-->
    <%# <div class="m-3">

      <!--printing window-->
      <button onclick="window.print()" class="print">Print this page</button>
      <!--printing window end-->
    </div> %>
    <!--Buttons end-->
    <div class="col-lg-3 recipe-image">
      <div class="img-food image-effect" data-controller="image-popup">
        <% if @recipe.photo.attached? %>
            <%= cl_image_tag @recipe.photo.key, class: "img-food", data: { bs_target: '#imageModal', bs_toggle: 'modal' } %>
        <% else %>
            <img class="img-food" src="https://d16kd6gzalkogb.cloudfront.net/magazine_images/Floris-Van-Dyck-Painting-Still-life-With-Fruit-Nuts-And-Cheese-via-flickr-com.jpg" alt="Food">
        <% end %>
      </div>
    </div>

    <div class="col-lg-3 recipe-ingredients">
      <h4 class="recipe-ingredients">Ingredients:</h4>
      <p class="recipe-ingredients-list"><% @recipe.recipes_ingredients.each do |recipe_ingredient| %>
        <li><%= recipe_ingredient.ingredient.name.capitalize  %> | <%= recipe_ingredient.quantity %></li>
      <% end %></p>
    </div>

    <div class="col-lg-6 recipe-prep">
      <%# <h3>Preparation: </h3> %>
      <div class="page">
        <p><span class="caps"><%= @recipe.instructions[0] %></span>
        <%= @recipe.instructions[1..] %></p>
      </div>
    </div>
  </div>

  <br>
  <br>

  <div class="row">
    <%# MAP %>
    <div class="container-map-centering">
      <div id="map" style="height: 300px; width: 600px; border-radius: 0px;" class="map-centering"
      data-mapbox-longitude-value="<%=@recipe.longitude %>"
      data-mapbox-latitude-value="<%=@recipe.latitude %>"
      data-mapbox-code-value="<%=@recipe.country_code %>"
      data-controller="mapbox" data-action="click->mapbox#map">
      </div>
    </div>
    <%# map-end %>
  </div>
</div>



<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <% if @recipe.photo.attached? %>
            <%= cl_image_tag @recipe.photo.key, class: "img-food-lg" %>
        <% else %>
            <img class="img-food-lg" src="https://d16kd6gzalkogb.cloudfront.net/magazine_images/Floris-Van-Dyck-Painting-Still-life-With-Fruit-Nuts-And-Cheese-via-flickr-com.jpg" alt="Food">
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/recipes/index.html.erb
  <%# <div class="recipe-text">recipes</div> %>
  <hr>
  <div class="container-99" data-controller="search">

    <div id="container-top">
      <%= render "search_form" %>
    </div>

  <div class="flex-container">
    <div class="box-1">
        <%= render "recipe_list" %>
    </div>

      <div class="recipe-container">
        <%= image_tag "Rectangle_12.jpg" , class: "bottom-image" %>
        <%# <img id="image" /> %>
      </div>
  </div>
</div>






<script>

//This script is changing photos
// var images = [
//    'https://user-images.githubusercontent.com/31392942/156794680-314e4839-4fe3-46d0-bcd2-e62a893b6471.jpg',
//     "https://user-images.githubusercontent.com/31392942/156794847-626867f0-fdc1-40f2-813a-a2efda2705a3.jpg",
//     "https://user-images.githubusercontent.com/31392942/156794779-a91a9757-d639-49eb-9bcf-3c61ce441574.jpg"
//    ];

// function randImg() {
//     var size = images.length
//     var x = Math.floor(size * Math.random())
//     document.getElementById('image').src= images[x];
// }

// randImg();


// </script>

app/views/recipes/new.html.erb
<hr>
<div class="container" data-controller="recipe-form">
  <div class="row container-controller">
    <div class="col-5 border-end">
      <h2 class="text-center mb-3">Recipe Creation</h2>
      <%= simple_form_for(@recipe) do |f| %>
          <%= f.input :name, label: "Name of the recipe", class: "text-center",
              input_html: { data: { action: "blur->recipe-form#updateName" } } %>
       <!--   <p class="mb-2">By <%=current_user.name %></p> -->
          <%= f.input :prep_time, class:"recipe-prep-time",
              input_html: { data: { action: "blur->recipe-form#updatePrepTime" } } %>
          <%= f.input :era, class:"recipe-era",
              input_html: { data: { action: "blur->recipe-form#updateEra" } }  %>
          <%= f.input :country, as: :string, class:"recipe-country",
              input_html: { data: { action: "blur->recipe-form#updateCountry" } } %>
          <%= f.input :country_code, as: :string %>
          <%= f.label "ingredients", required: true %>
          <div>
            <%= f.simple_fields_for :recipes_ingredients do |recipes_ingredients_form| %>
              <%= render "recipes_ingredient_fields", f: recipes_ingredients_form %>
            <% end %>
            <div>
              <%= link_to_add_association "Add ingredient", f, :recipes_ingredients, class: "btn btn-default add-button" %>
            </div>
          </div>
          <%= f.input :instructions,
              input_html: { data: { action: "blur->recipe-form#updateInstructions" } }%>
          <%= f.input :photo, as: :file, label: "Select an image",
              input_html: { data: {  action: "change->recipe-form#readURL" } } %>
          <div class="text-center">
            <%= f.submit %>
          </div>
      <% end %>
    </div>
    <div class="col-7">
      <div class="row">
      <div class="col-12">
          <h2 class="text-center">Recipe Preview</h2>
        </div>
        <h3 class="recipe-name-new mt-4" data-recipe-form-target="nameField"></h3>
        <div class="col-7">
            <div class="col-lg-6 recipe-information d-flex justify-content-evenly mb-3">
              <div data-recipe-form-target="imgField" class="text-center">
              </div>
              <p class="recipe-prep-time" data-recipe-form-target="prepTimeField" style="font-size:16px;"></p>
              <br>
              <h5 class="recipe-era" data-recipe-form-target="eraField" style="font-size:16px;"></h5>

            </div>
          </div>
            <div class="col-5 recipe-ingredients-new">
                <h5 class="recipe-country-new" data-recipe-form-target="countryField"></h5>
              <div>
                <label class="form-label text required" for="recipe-ingredients">
                  <div class="recipe-ingredients-new" data-recipe-form-target="ingredientField" style="font-size:16px;">
                  <abbr title="required"></abbr>
                </div>
                </label>
              </div>
          <br>
        </div>
      </div>
          <div class="recipe-prep-new">
            <p data-recipe-form-target="instructionsField" style="font-size:16px;"></p>
          </div>
          <div data-recipe-form-target="imgField" class="text-center">
          </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container-fluid">
  <div class="row mt-0">
    <div class="col-4 left-part" data-controller="search">
        <div class="centerbar">
            <form action="/recipes" method="get" class="searchbar">
            <select multiple name="ingredients[]" data-controller="select2" data-search-target="input">
                  <% Ingredient.all.each do |ing|  %>
                    <option value="<%= ing.id %>"><%= ing.name.capitalize %></option>
                  <% end %>
            </select>
            </form>
        </div>
        <%=render "recipe_list" %>
    </div>

    <%# <div class="background-rectangle">
    </div> %>
    <div class="col-lg-8 recipe-container">
      <%= render "show_recipe" %>

    </div>

  </div>
  <%# Row for content %>

  </div>

app/views/shared/_navbar.html.erb
<div class="nav-bar">
  <div class="div1"> <%= link_to "Ancient Meals", root_path, class: "nav-link text-nowrap" %> </div>
  <div class="div3"> <%= link_to "Add Recipe", new_recipe_path, class: "nav-link text-nowrap" %></div>
  <div class="div2"> <%= link_to "Recipes", recipes_path, class: "nav-link" %></div>
  <div class="div4"> <%= link_to "Cookbook", cookbook_path, class: "nav-link text-nowrap" %></div>
  <div class="div5 nav-link" style="text-decoration: none;">
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, class: "sign-out-btn text-nowrap", method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: "sign-in-btn text-nowrap" %>
    <% end %>
  </div>
</div>